# Generated by Django 5.2.3 on 2025-06-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_buy_productimage_remove_buy_productname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('number', models.BigIntegerField()),
                ('payment', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=20)),
                ('productImage', models.URLField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('totalAmount', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
