# Generated by Django 5.2.3 on 2025-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_delete_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(),
        ),
    ]
