# Generated by Django 5.2.3 on 2025-06-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_productimage_alter_order_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productImage',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='productPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(),
        ),
    ]
