# Generated by Django 5.2.3 on 2025-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_productimage_alter_order_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productImage',
            field=models.CharField(max_length=200),
        ),
    ]
